/*
 * Project: f:\2017Project\game-cms
 * Created Date: Thursday June 7th 2018
 * Author: 17030360
 * Email:wdnybbz@163.com
 * Description:-----
 * EditLog:-----
 * Copyright (c) 2018 SN
 */

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

//AR活动管理
export const RECEIVE_ARACTIVITY_LIST_SUCCESS =
	"RECEIVE_ARACTIVITY_LIST_SUCCESS";
export const RECEIVE_ARACTIVITY_LIST_FAILURE =
	"RECEIVE_ARACTIVITY_LIST_FAILURE";
export const ADD_ARACTIVITY_SUCCESS = "ADD_ARACTIVITY_SUCCESS";
export const ADD_ARACTIVITY_FAILURE = "ADD_ARACTIVITY_FAILURE";
export const EDIT_ARACTIVITY_SUCCESS = "EDIT_ARACTIVITY_SUCCESS";
export const EDIT_ARACTIVITY_FAILURE = "EDIT_ARACTIVITY_FAILURE";
export const DELETE_ARACTIVITY_SUCCESS = "DELETE_ARACTIVITY_SUCCESS";
export const DELETE_ARACTIVITY_FAILURE = "DELETE_ARACTIVITY_FAILURE";

//扫一扫活动管理
export const RECEIVE_ACTIVITYSCAN_LIST_SUCCESS =
	"RECEIVE_ACTIVITYSCAN_LIST_SUCCESS";
export const RECEIVE_ACTIVITYSCAN_LIST_FAILURE =
	"RECEIVE_ACTIVITYSCAN_LIST_FAILURE";
export const ADD_ACTIVITYSCAN_SUCCESS = "ADD_ACTIVITYSCAN_SUCCESS";
export const ADD_ACTIVITYSCAN_FAILURE = "ADD_ACTIVITYSCAN_FAILURE";
export const EDIT_ACTIVITYSCAN_SUCCESS = "EDIT_ACTIVITYSCAN_SUCCESS";
export const EDIT_ACTIVITYSCAN_FAILURE = "EDIT_ACTIVITYSCAN_FAILURE";
export const DELETE_ACTIVITYSCAN_SUCCESS = "DELETE_ACTIVITYSCAN_SUCCESS";
export const DELETE_ACTIVITYSCAN_FAILURE = "DELETE_ACTIVITYSCAN_FAILURE";

//换脸活动管理
export const RECEIVE_ACTIVITYFACE_LIST_SUCCESS =
	"RECEIVE_ACTIVITYFACE_LIST_SUCCESS";
export const RECEIVE_ACTIVITYFACE_LIST_FAILURE =
	"RECEIVE_ACTIVITYFACE_LIST_FAILURE";
export const ADD_ACTIVITYFACE_SUCCESS = "ADD_ACTIVITYFACE_SUCCESS";
export const ADD_ACTIVITYFACE_FAILURE = "ADD_ACTIVITYFACE_FAILURE";
export const EDIT_ACTIVITYFACE_SUCCESS = "EDIT_ACTIVITYFACE_SUCCESS";
export const EDIT_ACTIVITYFACE_FAILURE = "EDIT_ACTIVITYFACE_FAILURE";
export const DELETE_ACTIVITYFACE_SUCCESS = "DELETE_ACTIVITYFACE_SUCCESS";
export const DELETE_ACTIVITYFACE_FAILURE = "DELETE_ACTIVITYFACE_FAILURE";
export const WATCH_ACTIVITYFACE_SUCCESS = "WATCH_ACTIVITYFACE_SUCCESS";
export const WATCH_ACTIVITYFACE_FAILURE = "WATCH_ACTIVITYFACE_FAILURE";
export const TEMPLIST_SUCCESS = "TEMPLIST_SUCCESS";
export const TEMPLIST_FAILURE = "TEMPLIST_FAILURE";
export const UPLOADRES_SUCCESS = "UPLOADRES_SUCCESS";
export const UPLOADRES_FAILURE = "UPLOADRES_FAILURE";

//聚合页管理
export const RECEIVE_UNIONPAGE_LIST_SUCCESS = "RECEIVE_UNIONPAGE_LIST_SUCCESS";
export const RECEIVE_UNIONPAGE_LIST_FAILURE = "RECEIVE_UNIONPAGE_LIST_FAILURE";
export const MODIFY_UNIONPAGE_SUCCESS = "MODIFY_UNIONPAGE_SUCCESS";
export const MODIFY_UNIONPAGE_FAILURE = "MODIFY_UNIONPAGE_FAILURE";

//模板管理
export const RECEIVE_TEMPLATECONF_LIST_SUCCESS =
	"RECEIVE_TEMPLATECONF_LIST_SUCCESS";
export const RECEIVE_TEMPLATECONF_LIST_FAILURE =
	"RECEIVE_TEMPLATECONF_LIST_FAILURE";
export const MODIFY_TEMPLATECONF_LIST_SUCCESS =
	"MODIFY_TEMPLATECONF_LIST_SUCCESS";
export const MODIFY_TEMPLATECONF_LIST_FAILURE =
	"MODIFY_TEMPLATECONF_LIST_FAILURE";

//用户管理
export const RECEIVE_USER_LIST_SUCCESS = "RECEIVE_USER_LIST_SUCCESS";
export const RECEIVE_USER_LIST_FAILURE = "RECEIVE_USER_LIST_FAILURE";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
export const RECEIVE_USER_ITEM_SUCCESS = "RECEIVE_USER_ITEM_SUCCESS";
export const RECEIVE_USER_ITEM_FAILURE = "RECEIVE_USER_ITEM_FAILURE";

//权限管理
export const RECEIVE_AUTHORITY_LIST_SUCCESS = "RECEIVE_AUTHORITY_LIST_SUCCESS";
export const RECEIVE_AUTHORITY_LIST_FAILURE = "RECEIVE_AUTHORITY_LIST_FAILURE";
export const ADD_AUTHORITY_SUCCESS = "ADD_AUTHORITY_SUCCESS";
export const ADD_AUTHORITY_FAILURE = "ADD_AUTHORITY_FAILURE";
export const EDIT_AUTHORITY_SUCCESS = "EDIT_AUTHORITY_SUCCESS";
export const EDIT_AUTHORITY_FAILURE = "EDIT_AUTHORITY_FAILURE";
export const DELETE_AUTHORITY_SUCCESS = "DELETE_AUTHORITY_SUCCESS";
export const DELETE_AUTHORITY_FAILURE = "DELETE_AUTHORITY_FAILURE";

//角色管理
export const RECEIVE_ROLE_LIST_SUCCESS = "RECEIVE_ROLE_LIST_SUCCESS";
export const RECEIVE_ROLE_LIST_FAILURE = "RECEIVE_ROLE_LIST_FAILURE";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const ADD_ROLE_FAILURE = "ADD_ROLE_FAILURE";
export const MODIFY_ROLE_SUCCESS = "MODIFY_ROLE_SUCCESS";
export const MODIFY_ROLE_FAILURE = "MODIFY_ROLE_FAILURE";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAILURE = "DELETE_ROLE_FAILURE";
export const RECEIVE_ROLEAUTH_LIST_SUCESS = "RECEIVE_ROLEAUTH_LIST_SUCESS";
export const RECEIVE_ROLEAUTH_LIST_FAILURE = "RECEIVE_ROLEAUTH_LIST_FAILURE";
export const RECEIVE_ROLE_ITEM_SUCCESS = "RECEIVE_ROLE_ITEM_SUCCESS";
export const RECEIVE_ROLE_ITEM_FAILURE = "RECEIVE_ROLE_ITEM_FAILURE";
export const CHECKED_AUTHORITY_LIST = "CHECKED_AUTHORITY_LIST";
